config/routes.rb
Rails.application.routes.draw do
  root "feed#show"

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  resource :profile, only: [:show, :update],
    controller: "users"

  namespace :users do
    patch "change_password", to: "passwords#update"
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/models/app_session.rb
# app_session for cookies
class AppSession < ApplicationRecord
  belongs_to :user

  has_secure_password :token, validations: false

  before_create {
    self.token = self.class.generate_unique_secure_token
  }

  def to_h
    {
      user_id: user.id,
      app_session: id,
      token: self.token
    }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include MessageVerifier
  primary_abstract_class
end

app/models/concerns/message_verifier.rb
module MessageVerifier
  extend ActiveSupport::Concern

  class_methods do
    def message_verifier
      Rails.application.message_verifier(name)
    end
  end

  private

  def message_verifier
    Rails.application.message_verifier(self.class.name)
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user, :app_session, :organization
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user # source: :user tells active record to use user_id
end

app/models/user.rb
class User < ApplicationRecord
  include  PasswordReset

  validates :name, presence: true
  validates :email,
    format: { with: URI::MailTo::EMAIL_REGEXP },
    uniqueness: { case_sensitive: false }

  # Relationship
  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships

  before_validation :strip_extra_spaces

  has_secure_password
  validates :password, on: [:create, :password_change], presence: true, length: { minimum: 8 }

  has_many :app_sessions

  def self.create_app_session(email:, password:)
    return nil unless user = User.find_by(email: email.downcase)

    user.app_sessions.create if user.authenticate(password)
  end

  def authenticate_app_session(app_session_id, token)
    app_sessions.find(app_session_id).authenticate_token(token)
  rescue ActiveRecord::RecordNotFound
    nil
  end

  private

  def strip_extra_spaces
    self.name = self.name&.strip
    self.email = self.email&.strip
  end
end

app/models/user/password_reset.rb
module User::PasswordReset
  extend ActiveSupport::Concern

  included do
    has_secure_password :password_reset_token, validations: false

    before_save -> { self.password_reset_token = nil },
      if: -> { password_digest_change_to_be_saved.present? }
  end

  class_methods do
    def find_by_password_reset_id(id)
      message_verifier.verified(
        CGI.unescape(id),
        purpose: :password_reset
      )&.symbolize_keys => { user_id:, password_reset_token:}

      User.find(user_id)
          .authenticate_password_reset_token(password_reset_token)
    rescue ActiveRecord::RecordNotFound, NoMatchingPatternError
      nil
    end
  end


  def reset_password
    update(
      password_reset_token: self.class.generate_unique_secure_token
    )
    app_sessions.destroy_all

    send_password_reset_email
  end

  private

  def send_password_reset_email
    UserMailer.with(user: self)
              .password_reset(CGI.escape(password_reset_id))
              .deliver_now
  end

  def password_reset_id
    message_verifier.generate({
      user_id: id,
      password_reset_token: password_reset_token
    }, purpose: :password_reset, expires_in: 2.hours)
  end
end

app/models/user/password_reset_test.rb
require "test_helper"

class User:PasswordResetTest < ActiveSupport::TestCase
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticate

  helper_method :turbo_frame_request?
  helper_method :turbo_native_app?
end

app/controllers/concerns/authenticate.rb
module Authenticate
  extend ActiveSupport::Concern

  included do
    before_action :authenticate
    before_action :require_login, unless: :logged_in?

    helper_method :logged_in?
  end

  class_methods do
    def skip_authentication(**options)
      skip_before_action :authenticate, options
      skip_before_action :require_login, options
    end

    def allow_unauthenticated(**options)
      skip_before_action :require_login, options
    end
  end

  protected

  def logged_in?
    Current.user.present?
  end

  def log_in(app_session)
    cookies.encrypted.permanent[:app_session] = {
      value: app_session.to_h
    }
  end

  def log_out
    Current.app_session&.destroy
  end

  private

  def require_login
    flash.now[:notice] = t('login_required')
    render 'sessions/new', status: :unauthorized
  end

  def authenticate
    Current.app_session = authenticate_using_cookie
    Current.user = Current.app_session&.user
  end

  def authenticate_using_cookie
    app_session = cookies.encrypted[:app_session]
    authenticate_using app_session&.with_indifferent_access
  end

  def authenticate_using(data)
    # Ruby 3 rightward assignment
    data => { user_id:, app_session:, token: }

    user = User.find(user_id)
    user.authenticate_app_session(app_session, token)
  rescue NoMatchingPatternError, ActiveRecord::RecordNotFound
    nil
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  allow_unauthenticated

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_authentication only: [:new, :create]

  def new
  end

  def create
    @app_session = User.create_app_session(
      email: login_params[:email],
      password: login_params[:password]
    )

    if @app_session
      log_in(@app_session)

      flash[:success] = t('.success')
      redirect_to root_path, status: :see_other
    else
      flash.now[:danger] = t('.incorrect_details')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    log_out

    flash[:success] = t('.success')
    redirect_to root_path, status: :see_other
  end

  private

  def login_params
    @login_params ||= params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_authentication only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @organization = Organization.create(members: [@user])
      @app_session = @user.app_sessions.create
      log_in(@app_session)

      redirect_to root_path, status: :see_other, flash: { success: t(".welcome", name: @user.name) }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = Current.user
  end

  def update
    @user = Current.user

    if @user.update(update_params)
      flash[:success] = t(".success")
      redirect_to profile_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    return t("sokko") unless content_for?(:title)

    "#{content_for(:title)} | #{t('sokko')}"
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users/password_resets_helper.rb
module Users::PasswordResetsHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= render "shared/flashes" %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flashes.html.erb
<div class="container is-fluid" data-turbo-cache="false">
    <% flash.each do |level, message| %>
        <%= tag.div class: "notification is-#{level} is-light has-text-centered mt-4" do%>
            <%= message %>
        <% end %>
    <% end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar is-link" data-controller="navbar">
    <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
            <strong class="is-size-3">Sokko</strong>
        <% end %>
        <a role="button" class="navbar-burger" data-navbar-target="burger" data-action="navbar#toggle">
            <span></span>
            <span></span>
            <span></span>
        </a>
    </div>

    <navbar-menu class="navbar-menu" data-navbar-target="menu">
        <div class="navbar-start">
            <%= link_to t(".create_ad"), "#", class: "navbar-item" %>
            <%= link_to t(".messages"), "#", class: "navbar-item" if logged_in? %>
        </div>

        <div class="navbar-end">
            <%= tag.div class: "navbar-item has-dropdown is-hoverable mr-4" do%>
                <%= link_to Current.user.name, profile_path, id: "current_user_name",  class: "navbar-link" %>

                <div class="navbar-dropdown is-right">
                    <%= link_to t(".profile"), profile_path, class: "navbar-item" %>
                    <%= link_to t(".my_ads"), "#", class: "navbar-item" %>
                    <%= link_to t(".saved_ads"), "#", class: "navbar-item" %>

                    <hr class="navbar-divider">

                    <%= link_to t(".logout"), logout_path, class: "navbar-item", data: { turbo_method: :delete } %>
                </div>
            <% end if logged_in? %>

            <%= tag.div class: "navbar-item" do%>
                <div class="buttons">
                    <%= link_to t(".sign_up"), sign_up_path, class: "button is-primary" %>
                    <%= link_to t(".login"), login_path, class: "button is-light" %>
                </div>
            <% end unless logged_in?%>
        </div>
    </navbar-menu>
</nav>